package consts

const (
	ReqObjKey      = "reqObj"
	LevelInfo      = "info"
	LevelDebug     = "debug"
	LevelWarn      = "warn"
	LevelError     = "error"
	LblMsg         = "context"
	LblMessage     = "message"
	LblApplication = "application"
	LblScheme      = "scheme"
	LblTransaction = "transaction"
	LblStatus      = "status"
	LblCustomTag   = "customTag"
	LblServiceName = "serviceName"
	LblClientIP    = "clientIP"
	LblMethod      = "method"
	LblDuration    = "duration"
	LblBody        = "body"
	LblRequestId   = "requestId"
	LblTableId     = "tableId"
	LblUserId      = "userId"
	LblWorkspaceId = "workspaceId"
	LblToken       = "token"
	LblQuery       = "query"
	LblDate        = "date"
	LblError       = "err"
	LblGrpcStatus  = "grpc.status"
)
